version: '3.5'

services:

  mysql:
    image: mysql
    container_name: mysql_mediscreen
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: smashed31
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

    ports:
      - 3307:3306
    volumes:
      - mysql_db:/data/db




volumes:

  mysql_db: